image: node:6.11.4

services:
  - mongo:latest

variables:
  MONGO_DB: testdreamshare

stages:
  - build
  - lint
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - rm -rf node_modules
    - npm install
  artifacts:
    paths:
      - node_modules/

eslint:
  stage: lint
  script:
    - ./node_modules/.bin/eslint .


backend_tests:
  stage: test
  script:
    - npm test

#frontend_tests:
#  image: cypress/base
#  stage: test
#  script:
#    - npm run cypress

deploy_production:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh -p22 root@95.85.7.126 "rm -rf /root/_tmp"
    - ssh -p22 root@95.85.7.126 "mkdir /root/_tmp"
    - ssh -p22 root@95.85.7.126 "mkdir /root/_tmp/node_modules"
    - ssh -p22 root@95.85.7.126 "git clone git@gitlab.com:TiagoGrosso/LDSO /root/_tmp"
    - scp -P22 -r node_modules/* root@95.85.7.126:/root/_tmp/node_modules
    - ssh -p22 root@95.85.7.126 "mv /root/LDSO /root/_old && mv /root/_tmp /root/LDSO"
    - ssh -p22 root@95.85.7.126 "rm -rf /root/_old"
    - ssh -p22 root@95.85.7.126 "forever restartall"
  only:
    - master