image: node:6.11.4

services:
  - mongo:latest

variables:
  MONGO_DB: testdreamshare

stages:
  - build
  - lint
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - rm -rf node_modules
    - npm install
  artifacts:
    paths:
      - node_modules/

eslint:
  stage: lint
  script:
    - ./node_modules/.bin/eslint .


backend_tests:
  stage: test
  script:
    - npm test

frontend_tests:
  image: cypress/base
  stage: test
  script:
    - npm run cypress